// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package report

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Report struct {
	ID pgtype.UUID
}

type ReportPerson struct {
	ReportID   pgtype.UUID
	Name       string
	Surname    string
	Patronymic pgtype.Text
	Telegram   string
	Email      string
}

type ReportSkill struct {
	ReportID pgtype.UUID
	Skills   []byte
}

type ReportWork struct {
	ReportID      pgtype.UUID
	Position      string
	Grade         string
	GrowthMessage string
	TasksMessage  string
}
