// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package report

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateReport(ctx context.Context) (pgtype.UUID, error)
	CreateReportPerson(ctx context.Context, arg CreateReportPersonParams) error
	CreateReportSkills(ctx context.Context, arg CreateReportSkillsParams) error
	CreateReportWork(ctx context.Context, arg CreateReportWorkParams) error
	GetReport(ctx context.Context, id pgtype.UUID) (GetReportRow, error)
	GetReports(ctx context.Context, id pgtype.UUID) ([]GetReportsRow, error)
}

var _ Querier = (*Queries)(nil)
