// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report.sql

package report

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id)
VALUES (gen_random_uuid())
RETURNING id
`

func (q *Queries) CreateReport(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createReport)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createReportPerson = `-- name: CreateReportPerson :exec
INSERT INTO report_persons (
  report_id,
  name,
  surname,
  patronymic,
  telegram,
  email
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateReportPersonParams struct {
	ReportID   pgtype.UUID
	Name       string
	Surname    string
	Patronymic pgtype.Text
	Telegram   string
	Email      string
}

func (q *Queries) CreateReportPerson(ctx context.Context, arg CreateReportPersonParams) error {
	_, err := q.db.Exec(ctx, createReportPerson,
		arg.ReportID,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Telegram,
		arg.Email,
	)
	return err
}

const createReportSkills = `-- name: CreateReportSkills :exec
INSERT INTO report_skills (
  report_id, skills
) VALUES (
  $1,
  $2
)
`

type CreateReportSkillsParams struct {
	ReportID pgtype.UUID
	Skills   []byte
}

func (q *Queries) CreateReportSkills(ctx context.Context, arg CreateReportSkillsParams) error {
	_, err := q.db.Exec(ctx, createReportSkills, arg.ReportID, arg.Skills)
	return err
}

const createReportWork = `-- name: CreateReportWork :exec
INSERT INTO report_works (
  report_id,
  position,
  grade,
  growth_message,
  tasks_message
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
`

type CreateReportWorkParams struct {
	ReportID      pgtype.UUID
	Position      string
	Grade         string
	GrowthMessage string
	TasksMessage  string
}

func (q *Queries) CreateReportWork(ctx context.Context, arg CreateReportWorkParams) error {
	_, err := q.db.Exec(ctx, createReportWork,
		arg.ReportID,
		arg.Position,
		arg.Grade,
		arg.GrowthMessage,
		arg.TasksMessage,
	)
	return err
}

const getReport = `-- name: GetReport :one
SELECT reports.id, report_skills.report_id, report_skills.skills
FROM reports
JOIN report_skills ON reports.id = report_skills.report_id
WHERE reports.id = $1
LIMIT 1
`

type GetReportRow struct {
	ID       pgtype.UUID
	ReportID pgtype.UUID
	Skills   []byte
}

func (q *Queries) GetReport(ctx context.Context, id pgtype.UUID) (GetReportRow, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i GetReportRow
	err := row.Scan(&i.ID, &i.ReportID, &i.Skills)
	return i, err
}

const getReports = `-- name: GetReports :many
SELECT reports.id, report_skills.report_id, report_skills.skills
FROM reports
JOIN report_skills ON reports.id = skills.report_id
WHERE reports.id = $1
`

type GetReportsRow struct {
	ID       pgtype.UUID
	ReportID pgtype.UUID
	Skills   []byte
}

func (q *Queries) GetReports(ctx context.Context, id pgtype.UUID) ([]GetReportsRow, error) {
	rows, err := q.db.Query(ctx, getReports, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsRow
	for rows.Next() {
		var i GetReportsRow
		if err := rows.Scan(&i.ID, &i.ReportID, &i.Skills); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
